
homeassistant:
    name: Jardin2
    latitude: "colocar la latitud de la casa"
    longitude: "colocar la longitud de la casa"
    elevation: "colocar la elevacion de la ciudad" 
   # uniy_system: metric
    time_zone: America/Lima

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123
# Text to speech
tts:
  - platform: google_translate
    language: 'es'

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

switch:
 - platform: rpi_gpio
   invert_logic: true
   ports:
     5: electrovalvula
   
mqtt:
  broker: "colocar la ip del Raspberry"
  client_id: central
  discovery: true
    
sensor:


# Sensor de Suelo
 - platform: mqtt
   state_topic: "Home/Jardin2/Suelo1"
   name: "Suelo"
   value_template: "{{ value }}"
   unit_of_measurement: "%"

 # Sensor de Flujometro el caudal
 - platform: mqtt
   state_topic: "Home/Jardin2/CaudalP"
   name: "Caudal"
   value_template: "{{ value | float }}"
   unit_of_measurement: "L/min"

 # Sensor de Flujometro el consumo
 - platform: mqtt
   state_topic: "Home/Jardin2/ConsumoP"
   name: "Consumo"
   value_template: "{{ value | float}}"
   unit_of_measurement: "L"

  